name = "pillary-worker"
main = "src/index.ts"
compatibility_date = "2025-08-21"

routes = [
  { pattern = "inpinity.online/pillary/api/*", zone_name = "inpinity.online" },
  { pattern = "inpinity.online/pillary*", zone_name = "inpinity.online" }
]

[vars]
# Basis-Konfiguration
PAGES_HOST = "gallary-loader-inpinity.pages.dev"
JSON_BASE_CID = "bafybeibjqtwncnrsv4vtcnrqcck3bgecu3pfip7mwu4pcdenre5b7am7tu"  # Ordner mit 0.json..9999.json
IPFS_GATEWAYS = "https://cloudflare-ipfs.com,https://ipfs.io,https://ipfs.inpinity.online"

# Solana / Collection
COLLECTION_MINT = "6xvwKXMUGfkqhs1f3ZN3KkrdvLh2vF3tX1pqLo9aYPrQ"
COLLECTION_NAME = "Pi Pyramide"
COLLECTION_SYMBOL = "inpi"
COLLECTION_DESCRIPTION = "10000 Pi Pyramid blocks"
COLLECTION_CHAIN = "solana"
COLLECTION_STANDARD = "nft"
ME_COLLECTION_SLUG = "inpi"
COLLECTION_CERT_URL = "https://solscan.io/token/6xvwKXMUGfkqhs1f3ZN3KkrdvLh2vF3tX1pqLo9aYPrQ"

# Creator & RPC
CREATOR = "GEFoNLncuhh4nH99GKvVEUxe59SGe74dbLG7UUtfHrCp"
RPC = "https://api.mainnet-beta.solana.com"